data_args:
  cfg_path: ./config_files/config_hydra/motion_primitive/mp_h2_f8_r8.yaml
  data_dir: ./data/seq_data_zero_male
  dataset: mp_seq_v2
  enforce_gender: male
  enforce_zero_beta: 1
  feature_dim: 276
  future_length: 8
  history_length: 2
  num_primitive: 8
  prob_static: 0.0
  text_tolerance: 0.0
  weight_scheme: text_samp:0.
device: cuda
exp_name: mvae_fps_clip
model_args:
  activation: gelu
  arch: all_encoder
  dropout: 0.1
  ff_size: 1024
  h_dim: 256
  latent_dim: !!python/tuple
  - 1
  - 256
  nfeats: 276
  normalize_before: false
  num_heads: 4
  num_layers: 7
  position_embedding: learned
save_dir: !!python/object/apply:pathlib.PosixPath
- mvae
- mvae_fps_clip
seed: 0
torch_deterministic: true
track: 1
train_args:
  anneal_lr: 1
  batch_size: 128
  ema_decay: 0.999
  grad_clip: 1.0
  learning_rate: 0.0001
  log_interval: 1000
  resume_checkpoint: null
  save_interval: 50000
  stage1_steps: 100000
  stage2_steps: 50000
  stage3_steps: 50000
  use_amp: 0
  use_predicted_joints: 0
  val_interval: 10000
  weight_feature_rec: 0.0
  weight_joints_consistency: 10.0
  weight_joints_delta: 100.0
  weight_kl: 1.0e-06
  weight_latent_rec: 1.0
  weight_orient_delta: 100.0
  weight_rec: 1.0
  weight_smpl_joints_rec: 10.0
  weight_transl_delta: 100.0
wandb_entity: interaction
wandb_project_name: mld_vae
