python -m mld.train_mld_pae \
    --track 1 --exp_name 'mld_pae_Normphase_TR_babel_smplx' \
    --train_args.batch_size 1024 \
    --train_args.use_amp 1 \
    --data_args.dataset 'mp_seq_v2' \
    --data_args.data_dir './data/seq_data_zero_male' \
    --data_args.cfg_path './config_files/config_hydra/motion_primitive/mp_h2_f8_r4.yaml' \
    --denoiser_args.pae_type 'phase' \
    --denoiser_args.use_latent_norm 1 \
    --denoiser_args.mvae_path './mvae/mpae_babel_smplx/checkpoint_200000.pt' \
    --denoiser_args.train_rollout_type 'full' \
    --denoiser_args.train_rollout_history 'rollout' \
    --denoiser_args.model_type 'transformer' \
    --train_args.stage1_steps 100000 \
    --train_args.stage2_steps 100000 \
    --train_args.stage3_steps 100000 \
    --train_args.save_interval 100000 \
    --train_args.weight_latent_rec 1.0 \
    --train_args.weight_feature_rec 1.0 \
    --train_args.weight_smpl_joints_rec 0 \
    --train_args.weight_joints_consistency 0 \
    --train_args.weight_transl_delta 1e4 \
    --train_args.weight_joints_delta 1e4 \
    --train_args.weight_orient_delta 1e4 \
    --data_args.weight_scheme 'text_samp:0.' \