data_args:
  body_type: smplx
  cfg_path: ./config_files/config_hydra/motion_primitive/mp_h2_f8_r4.yaml
  data_dir: ./data/seq_data_zero_male_fd
  dataset: mp_seq_v2
  enforce_gender: male
  enforce_zero_beta: 1
  feature_dim: 276
  future_length: 8
  history_length: 2
  num_primitive: 4
  prob_static: 0.0
  text_tolerance: 0.0
  use_music_normalization: true
  weight_scheme: text_samp:0.
denoiser_args:
  diffusion_args:
    diffusion_steps: 10
    noise_schedule: cosine
    respacing: ''
    sigma_small: true
  model_args:
    activation: gelu
    clip_dim: 512
    cond_mask_prob: 0.1
    dropout: 0.1
    ff_size: 1024
    h_dim: 512
    history_shape: !!python/tuple
    - 2
    - 276
    noise_shape: !!python/tuple
    - 1
    - 256
    num_heads: 4
    num_layers: 8
  model_type: transformer
  mvae_path: ./mvae/mvae_babel_smplx/checkpoint_200000.pt
  rescale_latent: 1
  train_rollout_history: rollout
  train_rollout_type: full
device: cuda
exp_name: mld_babel_smplx
save_dir: !!python/object/apply:pathlib.PosixPath
- mld_denoiser
- transformer_mnorm
- mld_babel_smplx
seed: 0
torch_deterministic: true
track: 1
train_args:
  anneal_lr: 1
  batch_size: 1024
  ema_decay: 0.999
  grad_clip: 1.0
  learning_rate: 0.0001
  log_interval: 1000
  resume_checkpoint: null
  save_interval: 100000
  stage1_steps: 100000
  stage2_steps: 100000
  stage3_steps: 100000
  use_amp: 1
  use_predicted_joints: 0
  val_interval: 10000
  weight_feature_rec: 1.0
  weight_joints_consistency: 0.0
  weight_joints_delta: 10000.0
  weight_kl: 0.0001
  weight_latent_rec: 1.0
  weight_orient_delta: 10000.0
  weight_rec: 1.0
  weight_smpl_joints_rec: 0.0
  weight_transl_delta: 10000.0
wandb_entity: MangoBox
wandb_project_name: mld_denoiser
